//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMaps.App_Start
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_AGREntities : DbContext
    {
        public DB_AGREntities()
            : base("name=DB_AGREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgrField> AgrFields { get; set; }
        public virtual DbSet<AgrFieldLocation> AgrFieldLocations { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<PropertyType> PropertyTypes { get; set; }
        public virtual DbSet<Purpose> Purposes { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
    }
}
