//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMaps.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgrField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgrField()
        {
            this.AgrFieldLocations = new HashSet<AgrFieldLocation>();
        }
    
        public int FieldId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string CadastrNumber { get; set; }
        public int PropertyTypeId { get; set; }
        public float Area { get; set; }
        public Nullable<int> PurposeId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> COATAU { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgrFieldLocation> AgrFieldLocations { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual Purpose Purpose { get; set; }
        public virtual Region Region { get; set; }
    }
}
